ers_theme = function(){
  theme(line                  = element_line(colour = "black", size = 0.5, linetype = 1, lineend = "butt", arrow = FALSE),
        rect                  = element_rect(fill = "white", colour = NA, size = 0.5, linetype = 1),
        text                  = element_text(family = "sans", face = "plain", colour = "black", size = 9, hjust = 0.5, vjust = 0.5, angle = 0, lineheight = 0.9, margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "pt")),
        axis.title.x          = element_text(vjust = 1, margin = margin(t = 2.75, r = 0, b = 0, l = 0, unit = "pt")),
        axis.title.x.top      = element_text(vjust = 0, margin = margin(t = 0, r = 0, b = 2.75, l = 0, unit = "pt")),
        axis.title.y          = element_blank(),
        axis.text.x           = element_text(vjust = 1, margin = margin(t = 2.2, r = 0, b = 0, l = 0, unit = "pt")),
        axis.text.x.top       = element_text(vjust = 0, margin = margin(t = 0, r = 0, b = 2.2, l = 0, unit = "pt")),
        axis.text.y           = element_text(hjust = 1, margin = margin(t = 0, r = 2.2, b = 0, l = 0, unit = "pt")),
        axis.text.y.right     = element_text(hjust = 0, margin = margin(t = 0, r = 0, b = 0, l = 2.2, unit = "pt")),
        axis.ticks            = element_blank(),
        axis.line             = element_blank(),
        legend.margin         = margin(t = 5.5, r = 5.5, b = 5.5, l = 5.5, unit = "pt"),
        legend.spacing        = unit(11, units = "pt"),
        legend.key            = element_rect(fill = "white", colour = NA),
        legend.key.size       = unit(1.2, units = "lines"),
        legend.title          = element_text(hjust = 0, size = 9),
        legend.text           = element_text(size = 9),
        legend.position       = "bottom",
        legend.justification  = "center",
        legend.box.margin     = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.background = element_blank(),
        legend.box.spacing    = unit(11, units = "pt"),
        panel.background      = NULL,
        panel.border          = element_blank(),
        panel.spacing         = unit(5.5, units = "pt"),
        panel.grid.major.x    = element_blank(),
        panel.grid.minor.x    = element_blank(),
        panel.grid.major.y    = element_line(colour = "grey92"),
        panel.grid.minor.y    = element_line(size = rel(0.5)),
        plot.title            = element_text(face = "bold", size = 10.5, hjust = 0, vjust = 1, margin = margin(t = 5.5, r = 0, b = 5.5, l = 0, unit = "pt")),
        plot.title.position   = "plot",
        plot.subtitle         = element_text(hjust = 0, vjust = 1, margin = margin(t = 0, r = 0, b = 5, l = 0, unit = "pt")),
        plot.caption          = element_text(size = 8, hjust = 0, vjust = 1, margin = margin(t = 5.5, r = 0, b = 0, l = 0, unit = "pt")),
        plot.caption.position = "plot",
        plot.tag              = element_text(size = 8, hjust = 0, vjust = 0.5, margin = margin(t = 0, r = 0, b = 10, l = 0, unit = "pt")),
        plot.tag.position     = c(0,1),
        plot.margin           = margin(t = 10, r = 5.5, b = 5.5, l = 5.5, unit = "pt"),
        strip.background      = element_rect(fill = "grey85", colour = "grey20"),
        strip.placement       = "inside",
        strip.text            = element_text(colour = "grey10", size = rel(0.8), margin = margin(t = 4.4, r = 4.4, b = 4.4, l = 4.4, unit = "pt")),
        strip.text.y          = element_text(angle = -90),
        strip.switch.pad.grid = unit(2.75, units = "pt"),
        strip.switch.pad.wrap = unit(2.75, units = "pt"),
        strip.text.y.left     = element_text(angle = 90)
  )
}
